package me.ilucah.advancedarmor.armor;

public enum BoostType {

    EXP("exp"),
    MONEY("money"),
    COIN("coins"),
    TOKEN("tokens"),
    GEM("gems"),
    ESSENCE("essence"),
    SLIMES("slimes"),
    DIAMONDS("diamonds"),
    CHROME("chromes"),
    CLOUDS("clouds"),
    GOLD("gold"),
    IRON("iron"),
    ENERGY("energy"),
    PEARLS("pearls"),
    PLASTIC("plastic"),
    BALLS("balls"),
    GOALS("goals"),
    POWER("power"),
    TUNGSTEN("tungsten"),
    CUSTOM("custom"),
    CORES("cores"),
    SPINS("spins"),
    KEYS("keys"),
    DOORS("doors"),
    BELLS("bells"),
    NAILS("nails"),
    SLOTS("slots"),
    FLOWERS("flowers"),
    CANDY("candy"),
    LOLLIES("lollies"),
    ELECTRICITY("electricity"),
    FRUIT("fruit"),
    ORGANISMS("organisms"),
    PLANTS("plants"),
    CARS("cars"),
    VEHICLES("vehicles"),
    PASSES("passes"),
    RAINBOWS("rainbows"),
    BRONZE("bronze"),
    SILVER("silver"),
    POUNDS("pounds"),
    VOUCHERS("vouchers"),
    FRANCS("francs"),
    DOLLARS("dollars"),
    EUROS("euros"),
    YEN("yen"),
    STERLING("sterling"),
    METAL("metal"),
    COPPER("copper"),
    REDSTONE("redstone"),
    LAPIS_LAZULI("lapis_lazuli"),
    EMERALDS("emeralds"),
    RUBY("ruby"),
    OPALS("opals"),
    QUARTZ("quartz"),
    SAPPHIRES("sapphires"),
    OBSIDIAN("obsidian"),
    LIGHT("light"),
    UNAKITE("unakite"),
    MAGNESIUM("magnesium"),
    HEALTH("health"),
    HEARTS("hearts"),
    BERYL("beryl"),
    GLASS("glass"),
    NEGATIVES("negatives"),
    LIES("lies"),
    GEOTHITE("geothite"),
    CITRUS("citrus"),
    ALEXANDRITE("alexandrite"),
    CRYSTALS("crystals"),
    SILK("silk"),
    SUNS("suns"),
    MOONS("moons"),
    CUBES("cubes"),
    SPHERES("spheres"),
    GLOBES("globes"),
    DINERO("money"),
    FICHAS("tokens"),
    GEMAS("gems"),
    MONEDAS("coins"),
    CRISTALES("crystals"),
    ARGENT("money"),
    JETONS("tokens"),
    GEMMES("gems"),
    MONNAIE("coins"),
    CRISTAUX("crystals");

    private String s;

    BoostType(String s) {
        this.s = s;
    }

    public String getConfigKey() {
        return s;
    }
}